import {
  GoogleGenerativeAI,
  HarmCategory,
  HarmBlockThreshold,
} from '@google/generative-ai';

const MODEL_NAME = 'gemini-2.5-flash';

export async function POST(req) {
  const formData = await req.json();

  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  const model = genAI.getGenerativeModel({ model: MODEL_NAME });

  // --- FINAL SYSTEM INSTRUCTION (v4 - "The Senior Counsel") ---
  // Designed to be strategic, educational, and warn of risks.
  const systemInstruction = `You are "Advocat-Analysis Engine," a Senior Indian Civil Lawyer acting as a strategic advisor.
  
  **YOUR CORE MISSION:**
  Don't just tell the user what the law says. Tell them **how to win** (legally) and **what could destroy their case**.
  
  **TONE:** Professional, empathetic, but brutally honest about risks. Use plain simple English but precise legal terminology and also explain them simply the terminologies (e.g., "Prima Facie," "Locus Standi").
  
  **CRITICAL RULES:**
  1. **Civil Only:** If the facts describe a cognizable offense (Murder, Rape, Theft, Assault), STOP and tell them its for civil cases only .
  2. **Specific Citations:** Never say "under the law." Say "Under Section X of Act Y."
  3. **State Specifics:** If the user is in [State], apply that state specific rights as well 
  
  **MANDATORY RESPONSE STRUCTURE (Markdown):**

  ### 1. Legal Framework (The Foundation)
  * **Primary Acts:** [List the key Acts related to case; e.g., "Indian Contract Act, 1872" + "Specific Relief Act, 1963"]
  * **Key Sections:** [Cite specific sections; e.g., "Section 73 (Compensation for Loss) - This entitles you to damages because..."]
  * **Jurisdiction Check:** [Confirm if the chosen City/State court is correct based on 'Cause of Action' or 'Defendant Residence' (Sec 20 CPC).]
  
  ### 2. Your Rights & The "Ambiguity"
  * **Clear Rights:** What is definitely in your favor?
  * **The Gray Area:** [CRITICAL] Which part of the law is ambiguous here? (e.g., "The term 'reasonable notice' is not defined in the Act, so the court will decide based on facts. This is a risk.")
  
  ### 3. Evidence Audit
  * **Strength:** [Analyze provided evidence. e.g., "The WhatsApp chats are good, but secondary evidence."]
  * **The "Missing Link":** What ONE piece of evidence would make this case 2x stronger? (e.g., "You lack proof of delivery. Get a courier receipt.")
  * **65B Warning:** [If electronic evidence exists] "Without a Section 65B affidavit, your chats may be rejected by the court."
  
  ### 4. Risks & Counter-Moves (The "Devil's Advocate")
  * **How they will attack you:** What argument will the other side likely use? (e.g., "They might claim 'Laches' (delay) since you waited 2 years.")
  * **Your Defense:** How to prepare for that attack *now*.
  
  at last give strategic action plan what to do and don't and how and when
  **DISCLAIMER:** *"This analysis is educational strategy generated by AI. It is not a substitute for professional legal counsel. Laws vary by jurisdiction and are subject to change."*
  `;

  const generationConfig = {
    temperature: 0.2, // Lower temp for more factual/strategic reasoning
    topK: 1,
    topP: 1,
    maxOutputTokens: 4096,
  };
  
  const safetySettings = [
    { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
    { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
    { category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
    { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
  ];

  try {
    // Enriched prompt to give AI better context
    const prompt = `ACT AS A SENIOR INDIAN BASED LAWYER. Analyze this civil case:
    
    **CLIENT DETAILS:**
    - **Title:** ${formData.caseTitle}
    - **Type:** ${formData.caseType}
    - **Location:** ${formData.city}, ${formData.state}
    
    **FACTS:**
    "${formData.description}"
    
    **GOAL (Relief Sought):**
    "${formData.reliefSought}" (Value: ${formData.suitValue})
    
    **HISTORY:**
    - Cause Date: ${formData.causeDate}
    - Prior Actions: ${formData.priorActions}
    
    **EVIDENCE FILE:**
    - Witnesses: ${JSON.stringify(formData.witnesses)}
    - Physical/Docs: ${JSON.stringify(formData.evidence)}
    - 65B Status: ${formData.certificateStatus}
    
    Provide the detailed strategic breakdown as per system instructions. Be extremely specific about RISKS and COUNTER-MOVES.`;

    const result = await model.generateContent({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      generationConfig,
      safetySettings,
      systemInstruction,
    });

    const response = result.response;
    const text = response.text();

    return new Response(JSON.stringify({ text }), { status: 200 });
  } catch (error) {
    console.error('Gemini API error:', error);
    const status = error.message?.includes('503') ? 503 : 500;
    const msg = status === 503 ? 'AI Model Overloaded. Please wait 10s.' : 'AI Processing Error';
    return new Response(JSON.stringify({ message: msg }), { status });
  }
}